### ISSUE TITLE
using tensorboard 

### ISSUE THREAD

**Issue by Geli157** [LMozart/CVPR2023-DANI-Net#2]
When I replace wandb with tensorboard in the config file and run train.py I get the error AttributeError: occluding_bound. Does anyone know a solution to this problem?

**Comment by LMozart** [comment]
Hi There. I have updated the configuration files. It should be the missing occluding_bound attribute in the configuration file. (dataset->occluding_bound: False). Normally we set this as False. But for some objects with non-occluding boundaries, setting it as True will be better. Let me know if you have further problems :)

**Comment by Geli157** [comment]
Hello, your changes worked when I used wandb as logger_type. Thanks for that. 
But when I use tensorboard as logger_type and start train.py I get the following error: wandb.errors.Error: You must call wandb.init() before wandb.save()
Could you please help me with this error as well.

**Comment by LMozart** [comment]
Hi. Thank you for identifying the bug. If I am right, this error happens at the 500th epoch when saving the training weights. I have modified the code in utils/record_utils.py (add an "if" condition for wandb). Now it works well. Please let me know if there are further issues.

**Comment by Geli157** [comment]
Hi, I was able to run train.py with the logger_type= tensorboard without any error message. Thanks a lot for your help!

**Comment by LMozart** [comment]
Cool! No worries. Glad it works :)
