### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wh017** [LMozart/CVPR2023-DANI-Net#3]
您好，数据集Light Stage Data Gallery的链接关闭了连接，请问还有其他的方式获得这个数据集吗？

**Comment by LMozart** [comment]
您好，如果数据集链接无法访问，可以试试从百度网盘链接/Google Drive链接下载。我已经上传了数据集：
百度网盘：链接: https://pan.baidu.com/s/19gj9Xm25J-4jC1dCpx9EiA?pwd=1fdq 提取码: 1fdq 
Google Drive：https://drive.google.com/drive/folders/1S33U-tfVIIiiTbMFUbJVQPuZF1R3hQB1?usp=sharing
