### ISSUE TITLE
pre_trained_LNet

### ISSUE THREAD

**Issue by wh017** [LMozart/CVPR2023-DANI-Net#4]
你好，再次请教一下，预训练模型pre_trained_LNet可以自己训练吗？它的训练代码在哪里可以找到？

**Comment by LMozart** [comment]
您好，可以自己训练的。训练代码可以参考一下这个链接：https://github.com/junxuan-li/SCPS-NIR/blob/main/train_LNet.py
pre_trained_LNet直接来自这个repo

**Comment by wh017** [comment]
好的谢谢
