### ISSUE TITLE
diligent100的nml mae复现不出论文中的数值

### ISSUE THREAD

**Issue by Zong-chuy** [LMozart/CVPR2023-DANI-Net#5]
为什么您的代码在diligent100上跑出来的nml mae是19.5左右，跑了三次了还是19.5上下浮动

**Comment by LMozart** [comment]
您好，感谢您提出这个问题。如果您的观察是Bunny, Hexagon, Nut, Pentagon, Propeller, Square, 和Turbine这几个物体的数值普遍变差，这是因为我们的发布版代码中DataLoader第36行的数据集名称没有对上，导致边界法向量的监督出现了偏差。最新版本已经修复了该问题。如果还有问题，请您附上所有物体结果的截图。谢谢。详情请看：
LMozart/CVPR2023-DANI-Net@92710cd

**Comment by yangyuze1** [comment]
请问，您在diligent100上的法线评估是用了(255, 255)的GT还是(1001,1001)的GT？

**Comment by LMozart** [comment]
如您在[DiLiGenT100](https://photometricstereo.github.io/diligent102.html)评估网站上看到的，他会做一个降采样到(250, 250)之后再比较。我们提交的版本就是降采样之后的版本，应当是(250, 250)。

**Comment by Zong-chuy** [comment]
请问如何获得1001×1001的完整分辨率法线贴图呢？

**Comment by LMozart** [comment]
如果是指GT的法线贴图的话，DiLiGenT100没有提供。如果是指怎么获得高清的重建，需要在dataset_loader/load_diligent100.py中将降采样去掉。这会增加显存开销。有可能还需要把边界法向量约束的权重调大。https://github.com/LMozart/CVPR2023-DANI-Net/blob/92710cd671ef329164fdaf274266b769c1b9d1e3/utils/dataset_loader/load_diligent100.py#L57

**Comment by yangyuze1** [comment]
> 如您在[DiLiGenT100](https://photometricstereo.github.io/diligent102.html)评估网站上看到的，他会做一个降采样到(250, 250)之后再比较。我们提交的版本就是降采样之后的版本，应当是(250, 250)。

也就是说您论文中DiLiGenT100补充材料的实验都是基于（250，250）GT法线图，是吗? 我要引用您论文的实验做对比实验，希望把对比基准统一。

**Comment by LMozart** [comment]
是的
