### ISSUE TITLE
将DataLoader中的Anisotropic改成了Diligent100后，lgt int更差了是怎么回事？

### ISSUE THREAD

**Issue by Zong-chuy** [LMozart/CVPR2023-DANI-Net#6]
改之前的结果：（以steel为例）
ball_steel:nml mae:90.00, lgt mae:7.34, lgt int:3.3715: 100%|| 2000/2000 [32:39<00:00,  1.02it/s]
golf_steel:nml mae:90.00, lgt mae:6.17, lgt int:0.1186: 100%|| 2000/2000 [31:43<00:00,  1.05it/s]
spike_steel:nml mae:90.00, lgt mae:7.74, lgt int:0.3099: 100%|| 2000/2000 [33:24<00:00,  1.00s/it]
nut_steel:nml mae:90.00, lgt mae:6.61, lgt int:0.3103: 100%|| 2000/2000 [32:31<00:00,  1.03it/s]
square_steel:nml mae:90.00, lgt mae:33.13, lgt int:2.1237: 100%|| 2000/2000 [31:19<00:00,  1.06it/s]
pentagon_steel:nml mae:90.00, lgt mae:39.47, lgt int:1.1014: 100%|| 2000/2000 [31:16<00:00,  1.07it/s]
hexagon_steel:nml mae:90.00, lgt mae:21.00, lgt int:0.3638: 100%|| 2000/2000 [32:03<00:00,  1.04it/s]
propeller_steel:nml mae:90.00, lgt mae:9.83, lgt int:0.7872: 100%|| 2000/2000 [34:37<00:00,  1.04s/it]
turbine_steel:nml mae:90.00, lgt mae:5.17, lgt int:0.5174: 100%|| 2000/2000 [33:25<00:00,  1.00s/it]
bunny_steel:nml mae:90.00, lgt mae:6.41, lgt int:0.6404: 100%|| 2000/2000 [34:01<00:00,  1.02s/it]
改之后的结果：
ball_steel:nml mae:90.00, lgt mae:7.23, lgt int:3.3403: 100%|| 2000/2000 [36:40<00:00,  1.10s/it]
golf_steel:nml mae:90.00, lgt mae:6.21, lgt int:0.1210: 100%|| 2000/2000 [38:31<00:00,  1.16s/it]
spike_steel:nml mae:90.00, lgt mae:7.64, lgt int:0.0609: 100%|| 2000/2000 [35:29<00:00,  1.06s/it]
nut_steel:nml mae:90.00, lgt mae:6.28, lgt int:0.0922: 100%|| 2000/2000 [37:42<00:00,  1.13s/it]
square_steel:nml mae:90.00, lgt mae:40.33, lgt int:1.1577: 100%|| 2000/2000 [38:56<00:00,  1.17s/it]
pentagon_steel:nml mae:90.00, lgt mae:49.10, lgt int:6.4009: 100%|| 2000/2000 [35:36<00:00,  1.07s/it]
hexagon_steel:nml mae:90.00, lgt mae:12.00, lgt int:0.7330: 100%|| 2000/2000 [35:34<00:00,  1.07s/it]
propeller_steel:nml mae:90.00, lgt mae:41.71, lgt int:3.6645: 100%|| 2000/2000 [36:21<00:00,  1.09s/it]
turbine_steel:nml mae:90.00, lgt mae:28.44, lgt int:4.5529: 100%|| 2000/2000 [35:14<00:00,  1.06s/it]
bunny_steel:nml mae:90.00, lgt mae:9.91, lgt int:4.6513: 100%|| 2000/2000 [37:08<00:00,  1.11s/it]
不知道为什么我一直复现不出您论文中在diligent100数据集上的结果，即便将Anisotropic改成DiLiGenT100。

**Comment by LMozart** [comment]
您好，我们在对比发布版代码和我们之前跑实验时用的代码的区别，目前已经确定了一些会导致结果变差的bug，正在继续排查， 还需要一段时间

**Comment by LMozart** [comment]
我们已经修复了计算lgt int导致数值过高的bug，这是因为cal_ints_acc输入时第一个参数应当传的是gt的light intensity，而不是预测的light intensity。我们还更新了DiLiGenT100部分超参的设置，不过请注意当光源初始化很差时，部分物体准确率波动是正常现象，可以尝试换几个seed。详情请见：
LMozart/CVPR2023-DANI-Net@2c7d775

**Comment by Zong-chuy** [comment]
好的，十分感谢！请问您最新代码是如何保存mat文件的呢？
> 我们已经修复了计算lgt int导致数值过高的bug，这是因为cal_ints_acc输入时第一个参数应当传的是gt的light intensity，而不是预测的light intensity。我们还更新了DiLiGenT100部分超参的设置，不过请注意当光源初始化很差时，部分物体准确率波动是正常现象，可以尝试换几个seed。详情请见： [2c7d775](https://github.com/LMozart/CVPR2023-DANI-Net/commit/2c7d775)

**Comment by LMozart** [comment]
您好，烦请您再次查看新版代码中的models/tester.py和utils/record_utils.py两个文件中的内容。已添加了在测试程序中输出normal mat的功能
