### ISSUE TITLE
在Lightstage数据集上无法复现出论文的结果

### ISSUE THREAD

**Issue by wh017** [LMozart/CVPR2023-DANI-Net#7]
在Lightstage数据集上复现了三次，最好的一次结果是5.82/0.0955，4.22/0.1307，5.96/0.0946，6.80/0.2135，9.51/0.1973，8.99/0.2136，得不到论文中的结果，尤其是HELMET FRONT和KNIGHT FIGHTING，差的有点多，想请问下是什么原因造成的？
![image](https://github.com/LMozart/CVPR2023-DANI-Net/assets/68540117/b4839813-d6d1-408c-9f13-5bbb56dcc452)

**Comment by LMozart** [comment]
您好，烦请您查看最新的代码。效果不好主要是由于没有对整体的亮度值做一个缩放造成的（load_lightstage.py, line:74, 78）。我们发现原始的Light Stage在部分物体上亮度有些过低了。另一个点是在计算shadow的时候对三个骑士物体没有把光的方向从计算图中detach掉（runner.py, line:227），这是因为这三个骑士有相当一部分边界不满足occluding boundary的假设（比如：剑的部分），就会导致光源产生部分偏差
